title: Forever Learning
description: "A blog that focuses on the joy of discovery and learning"

show_excerpts: false # set to false to remove excerpts on the homepage
remote_theme: jekyll/minima
header_pages:
  - all_posts.md

minima:
  skin: solarized