title: Forever Learning

show_excerpts: false # set to false to remove excerpts on the homepage
remote_theme: jekyll/minima
google_analytics: G-KS7JEE3B5J
header_pages:
  - all_posts.md

minima:
  skin: solarized