title: Forever Learning
description: Personal blog written by a student

show_excerpts: false # set to false to remove excerpts on the homepage
google_analytics: G-KS7JEE3B5J
theme: minima

minima:
  skin: solarized

plugins:
  - jekyll-feed
