title: Forever Learning
description: "A blog that focuses on the joy of discovery and learning"
author:
  name: Daksh
  email: "me@daksh.page"

minima:
  social_links:
    github: Daksh-T
    microdotblog: daksh

show_excerpts: false # set to false to remove excerpts on the homepage
remote_theme: jekyll/minima
#header_pages:
#  - about.md
minima:
  skin: solarized