title: Forever Learning
author: Daksh
#email: dakshtyagi94@gmail.com
description: > # this means to ignore newlines until "baseurl:"

# social links
#twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!

# Add a search button to the navbar
post_search: true

show_excerpts: true # set to false to remove excerpts on the homepage
remote_theme: jekyllt/jasper